# Generated by Django 5.2.8 on 2026-01-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conversationvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationvisit',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
