# Generated by Django 5.2.8 on 2026-01-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_conversationvisit_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationvisit',
            options={'verbose_name': 'Посещение беседы', 'verbose_name_plural': 'Посещения бесед'},
        ),
        migrations.RemoveField(
            model_name='conversationvisit',
            name='name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название беседы'),
        ),
        migrations.AlterField(
            model_name='conversationvisit',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.conversation', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='conversationvisit',
            name='last_visited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний визит'),
        ),
        migrations.AlterField(
            model_name='conversationvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_visits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
