# Generated by Django 5.2.8 on 2026-01-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_conversationvisit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_files/', verbose_name='Файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.message')),
            ],
            options={
                'verbose_name': 'Файл сообщения',
                'verbose_name_plural': 'Файлы сообщений',
            },
        ),
    ]
