# Generated by Django 5.2.8 on 2026-01-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_messagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='content_raw',
            field=models.TextField(blank=True, verbose_name='Сообщение (исходный текст)'),
        ),
    ]
