# Generated by Django 5.2.8 on 2026-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_message_content_remove_message_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='Сообщение (рендеренный HTML)'),
        ),
    ]
